import { useEffect, useState } from "react";
import { addProperty, fetchDashboard, moderateReview, updateProperty } from "../api/admin";
import { useAuth } from "../context/authContext";
import "./Admin.css";

export default function Admin() {
  const { user } = useAuth(); const [data, setData] = useState(null); const [error, setError] = useState("");
  const [property, setProperty] = useState({ name: "", address: "", type: "apartment", description: "", rentMin: "", rentMax: "", pricePerSemester: "", distanceMi: "", bedrooms: "", amenities: "", photoUrl: "", parkingCost: "", insuranceCost: "", averageUtilities: "" });
  const [editingId, setEditingId] = useState(null);
  const load = () => fetchDashboard().then(setData).catch((err) => setError(err.message));
  const isStaff = user?.isAdmin || user?.isModerator;
  useEffect(() => { if (isStaff) load(); }, [isStaff]);
  if (!isStaff) return <main className="admin-page"><h1>Moderator access required</h1></main>;
  async function moderate(id, status) { const reason = status === "rejected" ? window.prompt("Reason for rejecting this review:") : ""; if (status === "rejected" && !reason) return; await moderateReview(id, status, reason); load(); }
  const emptyProperty = { name: "", address: "", type: "apartment", description: "", rentMin: "", rentMax: "", pricePerSemester: "", distanceMi: "", bedrooms: "", amenities: "", photoUrl: "", parkingCost: "", insuranceCost: "", averageUtilities: "" };
  function editProperty(item) { setEditingId(item.id); setProperty({ name: item.name, address: item.address, type: item.type, description: item.description || "", rentMin: item.rentMin || "", rentMax: item.rentMax || "", pricePerSemester: item.pricePerSemester || "", distanceMi: item.distanceMi || "", bedrooms: item.bedrooms || "", amenities: item.amenities.join(", "), photoUrl: item.photoUrl || "", parkingCost: item.parkingCost ?? "", insuranceCost: item.insuranceCost ?? "", averageUtilities: item.averageUtilities ?? "" }); window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" }); }
  function cancelEdit() { setEditingId(null); setProperty(emptyProperty); }
  async function saveProperty(event) { event.preventDefault(); const values = { ...property, amenities: property.amenities.split(",").map((x) => x.trim()).filter(Boolean) }; if (editingId) await updateProperty(editingId, values); else await addProperty(values); cancelEdit(); load(); }
  return <main className="admin-page"><p className="form-eyebrow">{user.isAdmin ? "Administrator" : "Moderator"} workspace</p><h1>PantherDen moderation</h1>{error && <p>{error}</p>}<div className="admin-stats">{data && Object.entries(data.counts).map(([label,value]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
    <section><h2>Pending review queue</h2>{data?.pendingReviews.map((review) => <article key={review.id}><div><strong>{review.title}</strong><span>{review.listingName} · {review.author} · {review.rating}/5</span><p>{review.reviewText}</p></div><aside><button onClick={() => moderate(review.id,"approved")}>Approve</button><button className="reject" onClick={() => moderate(review.id,"rejected")}>Reject</button></aside></article>)}{data?.pendingReviews.length === 0 && <p>No reviews waiting for moderation.</p>}</section>
    <section><h2>Property inventory</h2><div className="admin-properties">{data?.properties.map((item) => <div key={item.id}><span><strong>{item.name}</strong><small>{item.address} · {item.bedrooms ? `${item.bedrooms} bedroom${item.bedrooms === 1 ? "" : "s"}` : "Bedrooms not listed"}</small></span><button onClick={() => editProperty(item)}>Edit</button></div>)}</div></section>
    <section><h2>{editingId ? "Edit property" : "Add a property"}</h2><p className="admin-help">Store the exact bedroom count here. Student filters such as “2+” will include every property with two or more bedrooms. Parking, insurance, and utilities are optional monthly estimates used by the Budget page.</p><form onSubmit={saveProperty}>{["name","address","description","rentMin","rentMax","pricePerSemester","distanceMi","parkingCost","insuranceCost","averageUtilities","amenities","photoUrl"].map((name) => <label key={name}>{name.replace(/([A-Z])/g," $1")}<input name={name} type={["rentMin","rentMax","pricePerSemester","distanceMi","parkingCost","insuranceCost","averageUtilities"].includes(name) ? "number" : "text"} min={["parkingCost","insuranceCost","averageUtilities"].includes(name) ? "0" : undefined} step={name === "distanceMi" ? "0.1" : undefined} value={property[name]} onChange={(e) => setProperty({ ...property, [name]: e.target.value })} required={["name","address"].includes(name)} /></label>)}<label>Bedrooms<select value={property.bedrooms} onChange={(e) => setProperty({...property,bedrooms:e.target.value})}><option value="">Not listed</option>{[1,2,3,4,5,6].map((count) => <option key={count} value={count}>{count} bedroom{count === 1 ? "" : "s"}</option>)}</select></label><label>Type<select value={property.type} onChange={(e) => setProperty({...property,type:e.target.value})}><option value="apartment">Apartment</option><option value="dorm">Dorm</option></select></label><div className="admin-form-actions"><button type="submit">{editingId ? "Save changes" : "Add property"}</button>{editingId && <button type="button" className="secondary" onClick={cancelEdit}>Cancel</button>}</div></form></section>
    <section><h2>User directory</h2><div className="admin-users">{data?.users.map((account) => <div key={account.id}><span><strong>{account.name}</strong><small>{account.email}</small></span><span className="admin-role">{account.role} · {account.isVerified ? "verified" : "unverified"}</span></div>)}</div></section>
  </main>;
}
